ALTER TABLE customer
    ADD COLUMN phone VARCHAR(20),
    ADD COLUMN address TEXT,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
